#!/bin/sh

## Copyright (C) 2006-2013 Daniel Baumann <mail@daniel-baumann.ch>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


set -e

, /usr/share/lxc/lxc.functions

_LXC_DIRECTORY="${lxc_path}"

_OPTIONS="$(getopt -o n: -l name: -- "${@}")"

if [ "${?}" -ne 0 ]
then
	echo "Usage: $(basename ${0}) -n|--name CONTAINER" >&2
	exit 1
fi

eval set -- "${_OPTIONS}"

while true
do
	case "${1}" in
		-n|--name)
			_CONTAINER="${2}"
			shift 2
			;;

		--)
			shift
			break
			;;

		*)
			echo "E: $(basename ${0}): internal error ${0}" >&2
			exit 1
			;;
	esac
done

if [ -z "${_CONTAINER}" ]
then
	echo "E: $(basename ${0}): missing container name, use --name option" >&2
	exit 1
fi

if lxc-info -n ${_CONTAINER} 2>&1 | grep -qs "STOPPED"
then
	echo "P: ${_CONTAINER} - already stopped"
	exit 0
fi

if [ -e "${_LXC_DIRECTORY}/${_CONTAINER}/rootfs" ]
then
	chroot "${_LXC_DIRECTORY}/{_CONTAINER}/rootfs" telinit 0
else
	echo "E: ${_LXC_DIRECTORY}/${_CONTAINER}/rootfs - no such directory"
	exit 1
fi
