#!/bin/sh

## lxc-debconf - LXC template for Debian and Debian Derivatives
## Copyright (C) 2006-2012 Daniel Baumann <daniel@debian.org>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


set -e

if [ -e "${_TMPDIR}/debconf.default" ]
then
	. "${_TMPDIR}/debconf.default"
fi

if [ -e "${_PRESEED_FILE}" ]
then
	# Apply user specified preseed file
	debconf-set-selections "${_PRESEED_FILE}"
fi
