#!/bin/sh

## lxc-debconf - LXC template for Debian and Debian Derivatives
## Copyright (C) 2006-2012 Daniel Baumann <daniel@debian.org>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


set -e

# FIXME: this whole mess should be simplified at some point

. /usr/share/debconf/confmodule

Distribution ()
{
	db_get lxc-debconf/distribution
	_DISTRIBUTION="${RET}" # select

	if [ -z "${_DISTRIBUTION}" ]
	then
		case "${_MODE}" in
			debian)
				db_subst lxc-debconf/distribution CHOICES "Debian GNU/Linux 6.0 \"squeeze\", Debian GNU/Linux 7.0 \"wheezy\", Debian GNU/Linux unstable/sid"
				db_subst lxc-debconf/distribution CHOICES_C "squeeze, wheezy, sid"

				db_set lxc-debconf/distribution squeeze
				db_fset lxc-debconf/distribution seen false
				;;

			progress)
				db_subst lxc-debconf/distribution CHOICES "Progress Linux 1.0 (artax), Progress Linux 1.9 (artax-backports), Progress Linux 2.0 (baureo)"
				db_subst lxc-debconf/distribution CHOICES_C "artax, artax-backports, baureo"

				db_set lxc-debconf/distribution artax
				db_fset lxc-debconf/distribution seen false
				;;
		esac

		db_settitle lxc-debconf/title
		db_input high lxc-debconf/distribution || true
		db_go

		db_get lxc-debconf/distribution
		_DISTRIBUTION="${RET}" # select
	fi

	echo "_DISTRIBUTION=\"${_DISTRIBUTION}\"" >> "${_TMPDIR}/debconf.default"
	export _DISTRIBUTION
}

Parent_distribution ()
{
	db_get lxc-debconf/parent-distribution
	_PARENT_DISTRIBUTION="${RET}"

	if [ -z "${_PARENT_DISTRIBUTION}" ]
	then
		case "${_MODE}" in
			progress)
				case "${_DISTRIBUTION}" in
					artax*)
						_PARENT_DISTRIBUTION="squeeze"
						;;

					baureo*)
						_PARENT_DISTRIBUTION="sid"
						;;
				esac
				;;

			*)
				_PARENT_DISTRIBUTION="${_DISTRIBUTION}"
				;;
		esac
	fi

	echo "_PARENT_DISTRIBUTION=\"${_PARENT_DISTRIBUTION}\"" >> "${_TMPDIR}/debconf.default"
	export _PARENT_DISTRIBUTION
}

Architecture ()
{
	_CHOICES="${1}"
	_CHOICES_C="${2}"
	_DEFAULT="${3}"

	db_get lxc-debconf/architecture
	_ARCHITECTURE="${RET}" # select

	if [ -z "${_ARCHITECTURE}" ]
	then
		db_subst lxc-debconf/architecture CHOICES ${_CHOICES}
		db_subst lxc-debconf/architecture CHOICES_C ${_CHOICES_C}

		db_set lxc-debconf/architecture ${_DEFAULT}
		db_fset lxc-debconf/distribution seen false

		db_settitle lxc-debconf/title
		db_input high lxc-debconf/architecture || true
		db_go

		db_get lxc-debconf/architecture
		_ARCHITECTURE="${RET}" # select
	fi

	echo "_ARCHITECTURE=\"${_ARCHITECTURE}\"" >> "${_TMPDIR}/debconf.default"
	export _ARCHITECTURE
}

Archives ()
{
	db_get lxc-debconf/archives
	_ARCHIVES="${RET}" # multiselect

	if [ -z "${_ARCHIVES}" ]
	then
		case "${_MODE}" in
			debian)
				case "${_PARENT_DISTRIBUTION}" in
					sid)
						db_subst lxc-debconf/archives CHOICES "Debian Experimental"
						db_subst lxc-debconf/archives CHOICES_C "experimental"

						db_set lxc-debconf/archives ""
						db_fset lxc-debconf/archives seen false
						;;

					*)
						db_subst lxc-debconf/archives CHOICES "Debian Security, Debian Updates, Debian Backports, Debian Proposed Updates"
						db_subst lxc-debconf/archives CHOICES_C "${_DISTRIBUTION}-security, ${_DISTRIBUTION}-updates, ${_DISTRIBUTION}-backports, ${_DISTRIBUTION}-proposed-updates"

						db_set lxc-debconf/archives "${_DISTRIBUTION}-security, ${_DISTRIBUTION}-updates, ${_DISTRIBUTION}-backports"
						db_fset lxc-debconf/archives seen false
						;;
				esac
				;;

			progress)
				db_subst lxc-debconf/archives CHOICES "Progress (staging), Progress Security, Progress Security (staging), Progress Updates, Progress Updates (staging), Progress Backports, Progress Backports (staging)"
				db_subst lxc-debconf/archives CHOICES_C "${_DISTRIBUTION}-staging, ${_DISTRIBUTION}-security, ${_DISTRIBUTION}-security-staging, ${_DISTRIBUTION}-updates, ${_DISTRIBUTION}-updates-staging, ${_DISTRIBUTION}-backports, ${_DISTRIBUTION}-backports-staging"

				db_set lxc-debconf/archives "${_DISTRIBUTION}-security, ${_DISTRIBUTION}-updates, ${_DISTRIBUTION}-backports"
				db_fset lxc-debconf/archives seen false
				;;
		esac

		db_settitle lxc-debconf/title
		db_input high lxc-debconf/archives || true
		db_go

		db_get lxc-debconf/archives
		_ARCHIVES="${RET}" # multiselect
	fi

	_ARCHIVES="$(echo ${_ARCHIVES} | sed -e 's|, | |g')"

	echo "_ARCHIVES=\"${_ARCHIVES}\"" >> "${_TMPDIR}/debconf.default"
	export _ARCHIVES
}

Parent_archives ()
{
	db_get lxc-debconf/parent-archives
	_PARENT_ARCHIVES="${RET}" # multiselect (w/o empty)

	if [ -z "${_PARENT_ARCHIVES}" ]
	then
		case "${_MODE}" in
			progress)
				db_subst lxc-debconf/parent-archives CHOICES "Debian Security, Debian Updates , Debian Backports, Debian Proposed Updates"
				db_subst lxc-debconf/parent-archives CHOICES_C "${_DISTRIBUTION}-security, ${_DISTRIBUTION}-updates, ${_DISTRIBUTION}-backports, ${_DISTRIBUTION}-proposed-updates"

				db_set lxc-debconf/parent-archives "${_DISTRIBUTION}-security, ${_DISTRIBUTION}-updates, ${_DISTRIBUTION}-backports"
				db_fset lxc-debconf/parent-archives seen false

				db_settitle lxc-debconf/title
				db_input high lxc-debconf/parent-archives || true
				db_go
				;;

			*)
				db_subst lxc-debconf/parent-archives CHOICES "Debian Security, Debian Updates , Debian Backports, Debian Proposed Updates"
				db_subst lxc-debconf/parent-archives CHOICES_C "${_ARCHIVES}"

				db_set lxc-debconf/parent-archives "${_ARCHIVES}"
				db_fset lxc-debconf/parent-archives seen true
				;;
		esac

		db_get lxc-debconf/parent-archives
		_PARENT_ARCHIVES="${RET}" # multiselect (w/o empty)

		if [ -z "${_PARENT_ARCHIVES}" ]
		then
			case "${_MODE}" in
				progress)
					_PARENT_ARCHIVES="${_DISTRIBUTION}-security, ${_DISTRIBUTION}-updates, ${_DISTRIBUTION}-backports"
					;;

				*)
					_PARENT_ARCHIVES="${_ARCHIVES}"
					;;
			esac
		fi
	fi

	_PARENT_ARCHIVES="$(echo ${_PARENT_ARCHIVES} | sed -e 's|, | |g')"

	echo "_PARENT_ARCHIVES=\"${_PARENT_ARCHIVES}\"" >> "${_TMPDIR}/debconf.default"
	export _PARENT_ARCHIVES
}

Mirror ()
{
	db_get lxc-debconf/mirror
	_MIRROR="${RET}"

	if [ -z "${_MIRROR}" ]
	then
		case "${_MODE}" in
			debian)
				db_set lxc-debconf/mirror http://ftp.debian.org/debian/
				db_fset lxc-debconf/mirror seen false
				;;

			progress)
				db_set lxc-debconf/mirror http://cdn.archive.progress-linux.org/progress/
				db_fset lxc-debconf/mirror seen false
				;;
		esac

		db_settitle lxc-debconf/title
		db_input high lxc-debconf/mirror || true
		db_go

		db_get lxc-debconf/mirror
		_MIRROR="${RET}" # string (w/o empty)

		if [ -z "${_MIRROR}" ]
		then
			case "${_MODE}" in
				debian)
					_MIRROR="http://ftp.debian.org/debian/"
					;;

				progress)
					_MIRROR="http://cdn.archive.progress-linux.org/progress/"
					;;
			esac
		fi
	fi

	echo "_MIRROR=\"${_MIRROR}\"" >> "${_TMPDIR}/debconf.default"
	export _MIRROR
}

Mirror_security ()
{
	db_get lxc-debconf/mirror-security
	_MIRROR_SECURITY="${RET}" # string (w/o empty)

	if [ -z "${_MIRROR_SECURITY}" ]
	then
		case "${_MODE}" in
			debian)
				db_set lxc-debconf/mirror-security http://security.debian.org/
				db_fset lxc-debconf/mirror-security seen false
				;;

			*)
				db_set lxc-debconf/mirror-security ${_MIRROR}
				db_fset lxc-debconf/mirror-security seen true
				;;
		esac

		db_settitle lxc-debconf/title
		db_input high lxc-debconf/mirror-security || true
		db_go

		db_get lxc-debconf/mirror-security
		_MIRROR_SECURITY="${RET}" # string (w/o empty)

		if [ -z "${_MIRROR_SECURITY}" ]
		then
			case "${_MODE}" in
				debian)
					_MIRROR_SECURITY="http://security.debian.org/"
					;;

				*)
					_MIRROR_SECURITY="${_MIRROR}"
					;;
			esac
		fi
	fi

	echo "_MIRROR_SECURITY=\"${_MIRROR_SECURITY}\"" >> "${_TMPDIR}/debconf.default"
	export _MIRROR_SECURITY
}

Mirror_backports ()
{
	db_get lxc-debconf/mirror-backports
	_MIRROR_BACKPORTS="${RET}" # string (w/o empty)

	if [ -z "${_MIRROR_BACKPORTS}" ]
	then
		case "${_MODE}" in
			debian)
				db_set lxc-debconf/mirror-backports http://backports.debian.org/debian-backports/
				db_fset lxc-debconf/mirror-backports seen false
				;;

			*)
				db_set lxc-debconf/mirror-backports ${_MIRROR}
				db_fset lxc-debconf/mirror-backports seen true
				;;
		esac

		db_settitle lxc-debconf/title
		db_input high lxc-debconf/mirror-backports || true
		db_go

		db_get lxc-debconf/mirror-backports
		_MIRROR_BACKPORTS="${RET}" # string (w/o empty)

		if [ -z "${_MIRROR_BACKPORTS}" ]
		then
			case "${_MODE}" in
				debian)
					_MIRROR_BACKPORTS="http://backports.debian.org/debian-backports/"
					;;

				*)
					_MIRROR_BACKPORTS="${_MIRROR}"
					;;
			esac
		fi
	fi

	echo "_MIRROR_BACKPORTS=\"${_MIRROR_BACKPORTS}\"" >> "${_TMPDIR}/debconf.default"
	export _MIRROR_BACKPORTS
}

Parent_mirror ()
{
	db_get lxc-debconf/parent-mirror
	_PARENT_MIRROR="${RET}" # string (w/o empty)

	if [ -z "${_PARENT_MIRROR}" ]
	then
		case "${_MODE}" in
			progress)
				db_set lxc-debconf/parent-mirror http://ftp.debian.org/debian/
				db_fset lxc-debconf/parent-mirror seen false

				db_settitle lxc-debconf/title
				db_input high lxc-debconf/parent-mirror || true
				db_go
				;;

			*)
				db_set lxc-debconf/parent-mirror ${_MIRROR}
				db_fset lxc-debconf/parent-mirror seen true
				;;
		esac

		db_get lxc-debconf/parent-mirror
		_PARENT_MIRROR="${RET}" # string (w/o empty)

		if [ -z "${_PARENT_MIRROR}" ]
		then
			case "${_MODE}" in
				progress)
					_PARENT_MIRROR="http://ftp.debian.org/debian/"
					;;

				*)
					_PARENT_MIRROR="${_MIRROR}"
					;;
			esac
		fi
	fi

	echo "_PARENT_MIRROR=\"${_PARENT_MIRROR}\"" >> "${_TMPDIR}/debconf.default"
	export _PARENT_MIRROR
}

Parent_mirror_security ()
{
	db_get lxc-debconf/parent-mirror-security
	_PARENT_MIRROR_SECURITY="${RET}" # string (w/o empty)

	if [ -z "${_PARENT_MIRROR_SECURITY}" ]
	then
		case "${_MODE}" in
			progress)
				db_set lxc-debconf/parent-mirror-security http://security.debian.org/
				db_fset lxc-debconf/parent-mirror-security seen false

				db_settitle lxc-debconf/title
				db_input high lxc-debconf/parent-mirror-security || true
				db_go
				;;

			*)
				db_set lxc-debconf/parent-mirror-security ${_MIRROR_SECURITY}
				db_fset lxc-debconf/parent-mirror-security seen true
				;;
		esac

		db_get lxc-debconf/parent-mirror-security
		_PARENT_MIRROR_SECURITY="${RET}" # string (w/o empty)

		if [ -z "${_PARENT_MIRROR_SECURITY}" ]
		then
			case "${_MODE}" in
				progress)
					_PARENT_MIRROR_SECURITY="http://security.debian.org/"
					;;

				*)
					_PARENT_MIRROR_SECURITY="${_MIRROR_SECURITY}"
					;;
			esac
		fi
	fi

	echo "_PARENT_MIRROR_SECURITY=\"${_PARENT_MIRROR_SECURITY}\"" >> "${_TMPDIR}/debconf.default"
	export _PARENT_MIRROR_SECURITY
}

Parent_mirror_backports ()
{
	db_get lxc-debconf/parent-mirror-backports
	_PARENT_MIRROR_BACKPORTS="${RET}" # string (w/o empty)

	if [ -z "${_PARENT_MIRROR_BACKPORTS}" ]
	then
		case "${_MODE}" in
			progress)
				db_set lxc-debconf/parent-mirror-backports http://backports.debian.org/debian-backports/
				db_fset lxc-debconf/parent-mirror-backports seen false

				db_settitle lxc-debconf/title
				db_input high lxc-debconf/parent-mirror-backports || true
				db_go
				;;

			*)
				db_set lxc-debconf/parent-mirror-backports ${_MIRROR_BACKPORTS}
				db_fset lxc-debconf/parent-mirror-backports seen true
				;;
		esac

		db_get lxc-debconf/parent-mirror-backports
		_PARENT_MIRROR_BACKPORTS="${RET}" # string (w/o empty)

		if [ -z "${_PARENT_MIRROR_BACKPORTS}" ]
		then
			case "${_MODE}" in
				progress)
					_PARENT_MIRROR_BACKPORTS="http://backports.debian.org/debian-backports/"
					;;

				*)
					_PARENT_MIRROR_BACKPORTS="${_MIRROR_BACKPORTS}"
					;;
			esac
		fi
	fi

	echo "_PARENT_MIRROR_BACKPORTS=\"${_PARENT_MIRROR_BACKPORTS}\"" >> "${_TMPDIR}/debconf.default"
	export _PARENT_MIRROR_BACKPORTS
}

Archive_areas ()
{
	db_get lxc-debconf/archive-areas
	_ARCHIVE_AREAS="${RET}"

	if [ -z "${_ARCHIVE_AREAS}" ]
	then
		case "${_MODE}" in
			progress)
				db_subst lxc-debconf/archive-areas CHOICES "main, contrib, non-free"

				db_set lxc-debconf/archive-areas "main, contrib, non-free"
				db_fset lxc-debconf/archive-areas seen false
				;;

			*)
				db_subst lxc-debconf/archive-areas CHOICES "main, contrib, non-free"

				db_set lxc-debconf/archive-areas "main"
				db_fset lxc-debconf/archive-areas seen false
				;;
		esac

		db_settitle lxc-debconf/title
		db_input high lxc-debconf/archive-areas || true
		db_go

		db_get lxc-debconf/archive-areas
		_ARCHIVE_AREAS="${RET}" # multiselect (w/o empty)

		if [ -z "${_ARCHIVE_AREAS}" ]
		then
			case "${_MODE}" in
				debian)
					_ARCHIVE_AREAS="main"
					;;

				progress)
					_ARCHIVE_AREAS="main, contrib, non-free"
					;;
			esac
		fi
	fi

	_ARCHIVE_AREAS="$(echo ${_ARCHIVE_AREAS} | sed -e 's| ||g')"

	echo "_ARCHIVE_AREAS=\"${_ARCHIVE_AREAS}\"" >> "${_TMPDIR}/debconf.default"
	export _ARCHIVE_AREAS
}

Parent_archive_areas ()
{
	db_get lxc-debconf/parent-archive-areas
	_PARENT_ARCHIVE_AREAS="${RET}" # multiselect (w/o empty)

	if [ -z "${_PARENT_ARCHIVE_AREAS}" ]
	then
		case "${_MODE}" in
			progress)
				db_subst lxc-debconf/parent-archive-areas CHOICES "main, contrib, non-free"

				db_set lxc-debconf/parent-archive-areas "main, contrib, non-free"
				db_fset lxc-debconf/parent-archive-areas seen false

				db_settitle lxc-debconf/title
				db_input high lxc-debconf/parent-archive-areas || true
				db_go
				;;

			*)
				db_subst lxc-debconf/parent-archive-areas CHOICES "${_ARCHIVE_AREAS}"

				db_set lxc-debconf/parent-archive-areas "${_ARCHIVE_AREAS}"
				db_fset lxc-debconf/parent-archive-areas seen true
				;;
		esac

		db_get lxc-debconf/parent-archive-areas
		_PARENT_ARCHIVE_AREAS="${RET}" # multiselect (w/o empty)

		if [ -z "${_PARENT_ARCHIVE_AREAS}" ]
		then
			case "${_MODE}" in
				progress)
					_PARENT_ARCHIVE_AREAS="main, contrib, non-free"
					;;

				*)
					_PARENT_ARCHIVE_AREAS="${_ARCHIVE_AREAS}"
					;;
			esac
		fi
	fi

	_PARENT_ARCHIVE_AREAS="$(echo ${_PARENT_ARCHIVE_AREAS} | sed -e 's| ||g')"

	echo "_PARENT_ARCHIVE_AREAS=\"${_PARENT_ARCHIVE_AREAS}\"" >> "${_TMPDIR}/debconf.default"
	export _PARENT_ARCHIVE_AREAS
}

Packages ()
{
	db_get lxc-debconf/packages
	_PACKAGES="${RET}" # string (w/ empty)

	if [ -z "${_PACKAGES}" ]
	then
		db_settitle lxc-debconf/title
		db_input high lxc-debconf/packages || true
		db_go

		db_get lxc-debconf/packages
		_PACKAGES="${RET}" # string (w/ empty)
	fi

	echo "_PACKAGES=\"${_PACKAGES}\"" >> "${_TMPDIR}/debconf.default"
	export _PACKAGES
}

Local_repositories ()
{
	_NUMBER="0"

	while db_get lxc-debconf/local${_NUMBER}/repository && [ "${RET}" ]
	do
		mkdir -p "${_TMPDIR}/sources.list.d"

		_REPOSITORY="${RET#deb }"

		_LIST="local${_NUMBER}.list"
		if db_get lxc-debconf/local${_NUMBER}/list
		then
			_LIST="$(basename ${RET} .list).list"
		fi

		_COMMENT=""
		if db_get lxc-debconf/local${_NUMBER}/comment
		then
			_COMMENT="${RET}"

			echo "# ${_COMMENT}" > "${_TMPDIR}/sources.list.d/${_LIST}"
		fi

		echo "deb ${_REPOSITORY}" >> "${_TMPDIR}/sources.list.d/${_LIST}"

		if db_get lxc-debconf/local${_NUMBER}/source && [ "$RET" = true ]
		then
			echo "deb-src ${_REPOSITORY}" >> "${_TMPDIR}/sources.list.d/${_LIST}"
		fi

		_KEY=""
		if db_get lxc-debconf/local${_NUMBER}/key
		then
			_KEY="${RET}"

			wget -q "${_KEY}" -O "${_TMPDIR}/sources.list.d/$(basename ${_LIST} .list).key"
		fi

		_NUMBER="$((${_NUMBER} + 1))"
	done
}

Root_password ()
{
	if db_get passwd/root-password
	then
		_ROOT_PASSWORD="${RET}" # string (w/o empty)
	fi

	if [ -z "${_ROOT_PASSWORD}" ]
	then
		# Create a random password as suggestion for the user
		_RANDOM_PASSWORD="$(dd if=/dev/urandom bs=6 count=1 2> /dev/null | base64)"

		db_set passwd/root-password ${_RANDOM_PASSWORD}
		db_fset passwd/root-password seen false

		db_settitle lxc-debconf/title
		db_input high passwd/root-password || true
		db_go

		db_get passwd/root-password
		_ROOT_PASSWORD="${RET}"

		if [ -z "${_ROOT_PASSWORD}" ]
		then
			# User did set not set a password, falling back to random password
			_ROOT_PASSWORD="${_RANDOM_PASSWORD}"

			echo "_ROOT_RANDOM_PASSWORD=\"true\"" >> "${_TMPDIR}/debconf.default"
		fi
	fi

	echo "_ROOT_PASSWORD=\"${_ROOT_PASSWORD}\"" >> "${_TMPDIR}/debconf.default"
}

Network ()
{
	_NUMBER="0"

	while db_get live-debconfig/ifupdown/eth${_NUMBER}-method && [ "${RET}" ]
	do
		if db_get live-debconfig/ifupdown/eth${_NUMBER}-comment
		then
			eval LXC_DEBCONF_ETH${_NUMBER}_COMMENT="\"${RET}\"" # string (w/)
		fi

		if db_get lxc-debconf/eth${_NUMBER}-bridge
		then
			eval LXC_DEBCONF_ETH${_NUMBER}_BRIDGE="\"${RET}\"" # string (w/o empty)
		fi

		if db_get lxc-debconf/eth${_NUMBER}-mac
		then
			eval LXC_DEBCONF_ETH${_NUMBER}_MAC="\"${RET}\"" # string (w/o empty)
		fi

		if db_get lxc-debconf/eth${_NUMBER}-veth
		then
			eval LXC_DEBCONF_ETH${_NUMBER}_VETH="\"${RET}\"" # string (w/ empty)
		fi

		_NUMBER="$((${_NUMBER} + 1))"
	done

	# FIXME: this is ugly
	if [ "${_NUMBER}" -gt 0 ]
	then
		LXC_DEBCONF_ETH_NUMBER="$((${_NUMBER} - 1))"
	else
		LXC_DEBCONF_ETH_NUMBER="${_NUMBER}"
	fi

	if [ -z ${LXC_DEBCONF_ETH0_BRIDGE} ]
	then
		# FIXME: do guess the default bridge device
		db_set lxc-debconf/eth0-bridge br0
		db_fset lxc-debconf/eth0-bridge seen false

		db_settitle lxc-debconf/title
		db_input high lxc-debconf/eth0-bridge || true
		db_go

		db_get lxc-debconf/eth0-bridge
		LXC_DEBCONF_ETH0_BRIDGE="${RET:-br0}"
	fi

	if [ -z "${LXC_DEBCONF_ETH0_MAC}" ]
	then
		# FIXME: do guess the default mac address
		db_set lxc-debconf/eth0-mac 00:FF:00:00:00:01
		db_fset lxc-debconf/eth0-mac seen false

		db_settitle lxc-debconf/title
		db_input high lxc-debconf/eth0-mac || true
		db_go

		db_get lxc-debconf/eth0-mac
		LXC_DEBCONF_ETH0_MAC="${RET:-00:FF:00:00:00:01}"
	fi

	echo "LXC_DEBCONF_ETH_NUMBER=\"${LXC_DEBCONF_ETH_NUMBER}\"" >> "${_TMPDIR}/debconf.default"

	for _NUMBER in $(seq 0 ${LXC_DEBCONF_ETH_NUMBER})
	do
		eval _COMMENT="$`echo LXC_DEBCONF_ETH${_NUMBER}_COMMENT`"
		echo "LXC_DEBCONF_ETH${_NUMBER}_COMMENT=\"${_COMMENT}\"" >> "${_TMPDIR}/debconf.default"

		eval _BRIDGE="$`echo LXC_DEBCONF_ETH${_NUMBER}_BRIDGE`"
		echo "LXC_DEBCONF_ETH${_NUMBER}_BRIDGE=\"${_BRIDGE}\"" >> "${_TMPDIR}/debconf.default"

		eval _MAC="$`echo LXC_DEBCONF_ETH${_NUMBER}_MAC`"
		echo "LXC_DEBCONF_ETH${_NUMBER}_MAC=\"${_MAC}\"" >> "${_TMPDIR}/debconf.default"

		eval _VETH="$`echo LXC_DEBCONF_ETH${_NUMBER}_VETH`"
		echo "LXC_DEBCONF_ETH${_NUMBER}_VETH=\"${_VETH}\"" >> "${_TMPDIR}/debconf.default"
	done
}

Auto ()
{
	db_get lxc-debconf/auto
	_AUTO="${RET}" # boolean

	if [ -z "${_AUTO}" ]
	then
		db_set lxc-debconf/auto false
		db_fset lxc-debconf/auto seen false

		db_settitle lxc-debconf/title
		db_input high lxc-debconf/auto || true
		db_go

		db_get lxc-debconf/auto
		_AUTO="${RET}"
	fi

	echo "_AUTO=\"${_AUTO}\"" >> "${_TMPDIR}/debconf.default"
	export _AUTO
}

Internal_options ()
{
	if db_get lxc-debconf/apt-recommends
	then
		_APT_RECOMMENDS="${RET}" # boolean (w/ empty)
	fi

	echo "_APT_RECOMMENDS=\"${_APT_RECOMMENDS}\"" >> "${_TMPDIR}/debconf.default"

	if db_get lxc-debconf/debconf-frontend
	then
		_DEBCONF_FRONTEND="${RET}" # select
	fi

	_DEBCONF_FRONTEND="${_DEBCONF_FRONTEND:-dialog}"
	echo "_DEBCONF_FRONTEND=\"${_DEBCONF_FRONTEND}\"" >> "${_TMPDIR}/debconf.default"

	if db_get lxc-debconf/debconf-priority
	then
		_DEBCONF_PRIORITY="${RET}" # select
	fi

	_DEBCONF_PRIORITY="${_DEBCONF_PRIORITY:-high}"
	echo "_DEBCONF_PRIORITY=\"${_DEBCONF_PRIORITY}\"" >> "${_TMPDIR}/debconf.default"

	if db_get lxc-debconf/late-command
	then
		_LATE_COMMAND="${RET}" # string (w/ empty)
	fi

	echo "_LATE_COMMAND=\"${_LATE_COMMAND}\"" >> "${_TMPDIR}/debconf.default"

	if db_get lxc-debconf/late-host-command
	then
		_LATE_HOST_COMMAND="${RET}" # string (w/ empty)
	fi

	echo "_LATE_HOST_COMMAND=\"${_LATE_HOST_COMMAND}\"" >> "${_TMPDIR}/debconf.default"

	if db_get lxc-debconf/capabilities
	then
		_CAPABILITIES="${RET}" # string (w/ empty)
	fi

	echo "_CAPABILITIES=\"${_CAPABILITIES}\"" >> "${_TMPDIR}/debconf.default"

	_NUMBER="0"

	while db_get lxc-debconf/mount${_NUMBER}/entry && [ "${RET}" ]
	do
		eval LXC_DEBCONF_MOUNT${_NUMBER}_ENTRY="\"${RET}\"" # string (w/o empty)

		if db_get lxc-debconf/mount${_NUMBER}/comment
		then
			eval LXC_DEBCONF_MOUNT${_NUMBER}_COMMENT="\"${RET}\"" # string (w/ empty)
		fi

		_NUMBER="$((${_NUMBER} + 1))"
	done

	# FIXME: this is ugly
	if [ "${_NUMBER}" -gt 0 ]
	then
		LXC_DEBCONF_MOUNT_NUMBER="$((${_NUMBER} - 1))"
	else
		LXC_DEBCONF_MOUNT_NUMBER="${_NUMBER}"
	fi

	echo "LXC_DEBCONF_MOUNT_NUMBER=\"${LXC_DEBCONF_MOUNT_NUMBER}\"" >> "${_TMPDIR}/debconf.default"

	for _NUMBER in $(seq 0 ${LXC_DEBCONF_MOUNT_NUMBER})
	do
		eval _COMMENT="$`echo LXC_DEBCONF_MOUNT${_NUMBER}_COMMENT`"
		echo "LXC_DEBCONF_MOUNT${_NUMBER}_COMMENT=\"${_COMMENT}\"" >> "${_TMPDIR}/debconf.default"

		eval _ENTRY="$`echo LXC_DEBCONF_MOUNT${_NUMBER}_ENTRY`"
		echo "LXC_DEBCONF_MOUNT${_NUMBER}_ENTRY=\"${_ENTRY}\"" >> "${_TMPDIR}/debconf.default"
	done
}

Distribution
Parent_distribution

case "$(dpkg --print-architecture)" in
	amd64)
		# Usage: Architecture CHOICES CHOICES_C Default
		Architecture "32-bit PC (i386), 64-bit PC (amd64)" "i386, amd64" "amd64"
		;;
esac

Archives
Parent_archives

Mirror

for _ARCHIVE in ${_ARCHIVES}
do
	case "${_ARCHIVE}" in
		*-security*)
			Mirror_security
			;;

		*-backports*)
			Mirror_backports
			;;
	esac
done

Parent_mirror

for _PARENT_ARCHIVE in ${_PARENT_ARCHIVES}
do
	case "${_PARENT_ARCHIVE}" in
		*-security)
			Parent_mirror_security
			;;

		*-backports)
			Parent_mirror_backports
			;;
	esac
done

Archive_areas
Parent_archive_areas

Packages
Local_repositories

Root_password
Network
Auto

Internal_options

db_stop
