#!/bin/sh

### BEGIN INIT INFO
# Provides:		lxc
# Required-Start:	$syslog $remote_fs
# Required-Stop:	$syslog $remote_fs
# Should-Start:
# Should-Stop:
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Linux Containers
# Description:		Linux Containers
# X-Start-Before:
# X-Stop-After:
# X-Interactive:	true
### END INIT INFO

if [ ! -x /usr/bin/lxc-start ] || [ ! -x /usr/bin/lxc-initscript ]
then
	exit 0
fi

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin

. /lib/lsb/init-functions

case "${1}" in
	start)
		lxc-initscript start
		;;

	stop)
		lxc-initscript stop
		;;

	restart|force-reload)
		lxc-initscript restart
		;;

	freeze)
		lxc-initscript freeze
		;;

	unfreeze)
		lxc-initscript unfreeze
		;;

	status)
		lxc-list
		;;

	*)
		log_success_msg "Usage: ${0} {start|stop|restart|force-reload|freeze|unfreeze|status}"
		exit 1
		;;
esac

exit 0
