#!/bin/sh

set -e

case "${1}" in
	purge)
		if [ -e /etc/default/lxc ]
		then
			. /etc/default/lxc
		fi

		LXC_DIRECTORY="${LXC_DIRECTORY:-/var/lib/lxc}"

		rm -f /etc/default/lxc

		rmdir --ignore-fail-on-non-empty "${LXC_DIRECTORY}" > /dev/null 2>&1 || true
		;;

	remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

		;;

	*)
		echo "postrm called with unknown argument \`${1}'" >&2
		exit 1
		;;
esac

#DEBHELPER#

exit 0
